### ISSUE TITLE
Wont Work

### ISSUE THREAD

**Issue by skizap** [Teklad/tuxdump#2]
can anyone help me?

└─ $ ▶ cmake ..
CMake Error at CMakeLists.txt:9 (find_package):
  Could not find a package configuration file provided by "TuxProc" with any
  of the following names:

    TuxProcConfig.cmake
    tuxproc-config.cmake

  Add the installation prefix of "TuxProc" to CMAKE_PREFIX_PATH or set
  "TuxProc_DIR" to a directory containing one of the above files.  If
  "TuxProc" provides a separate development package or SDK, be sure it has
  been installed.

-- Configuring incomplete, errors occurred!
See also "/home/atome/tuxdump/build/CMakeFiles/CMakeOutput.log".

**Comment by Teklad** [comment]
I made some changes to the build system a while back.  I think I got it fixed now.  I was testing with TuxProc installed on my system which wasn't intentional.  Sorry about that.

**Comment by skizap** [comment]
Thank you it works now:)

**Comment by Teklad** [comment]
No problem at all.  Let me know if you run into anymore issues.  I'll go ahead and close this one.  Cheers.
