### ISSUE TITLE
i get this

### ISSUE THREAD

**Issue by suciuale** [Teklad/tuxdump#3]
/tuxdump/src/formatter.cpp:6:10: fatal error: libconfig.h++: No such file or directory
 #include <libconfig.h++>
          ^~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/tuxdump.dir/build.make:62: recipe for target 'CMakeFiles/tuxdump.dir/src/formatter.cpp.o' failed
make[2]: *** [CMakeFiles/tuxdump.dir/src/formatter.cpp.o] Error 1
CMakeFiles/Makefile2:69: recipe for target 'CMakeFiles/tuxdump.dir/all' failed
make[1]: *** [CMakeFiles/tuxdump.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

halp ples? :(

**Comment by Teklad** [comment]
Did you follow the build instructions?  In particular you need to run:
`git submodule update --init --recursive`

It depends on 3rd party libraries in order to compile.

**Comment by Teklad** [comment]
Turned out this was an issue with the way I was handling the internal libconfig when it isn't installed on your system.  I pushed a commit which should fix this.  Thanks for the report.
