### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by telans** [Teklad/tuxdump#4]
Build error during "Linking CXX executable tuxdump"

Full console output: https://pastebin.com/raw/HeRWhnmL

I think this has something to do with a329696fd4a0729d4d9b386ee7746d045376dc41? libconfig++-dev is installed.

**Comment by Teklad** [comment]
They are probably sort-of related.  My guess is your version of libconfig++ doesn't come with the CMake file, and I forgot to set the pkg-config version when I made the update.  Shouldn't be a tough fix.

**Comment by Teklad** [comment]
Should be working with latest commit... simplified it down to rely on pkg-config only.  Let me know if you run into any issues.

**Comment by telans** [comment]
Builds a-okay. Cheers
