### ISSUE TITLE
Jun 4 2020 update broke something.

### ISSUE THREAD

**Issue by kusayuzayushko** [Teklad/tuxdump#5]
```
sudo ./tuxdump -fcpp signatures
Options:
    Config:         csgo.cfg       
    Format:         cpp            
    Process:        csgo_linux64   
    Tool:           signatures     
[1]    12119 segmentation fault  sudo ./tuxdump -fcpp signatures
```

**Comment by slowptr** [comment]
If you replace every "client_panorama_client.so" with "client_client.so" in your config (default=csgo.cfg) it should work.

**Comment by Teklad** [comment]
I'd accept a PR including this change to the default config. Currently working to much to properly maintain projects. Lol.

**Comment by tekladis** [comment]
Fixed in most recent PR.
